import type { Theme } from '../types/theme'

const catppuccinLatteTheme: Theme = {
  id: 'catppuccin_latte',
  name: '奶茶物语',
  isDark: false,
  colors: {
    primary: '#1e66f5',
    'primary-light': '#eff1f5',
    'primary-dark': '#1a4b8c',
    background: '#eff1f5',
    'background-light': '#e6e9ef',
    'background-dark': '#dce0e8',
    'surface-1': '#ffffff',
    'surface-2': '#eff1f5',
    'surface-3': '#e6e9ef',
    'surface-4': '#dce0e8',
    text: '#4c4f69',
    'text-secondary': '#8c8fa8',
    border: '#ccd0da',
    hover: 'rgba(30, 102, 245, 0.1)',
    header: '#e6e9ef',
    shadow: 'rgba(76, 79, 105, 0.1)',
    success: '#40a02b',
    warning: '#df8e1d',
    danger: '#d20f39',
    info: '#209fb5',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

const rosePineTheme: Theme = {
  id: 'rose_pine_dawn',
  name: '晨曦玫瑰',
  isDark: false,
  colors: {
    primary: '#907aa9',
    'primary-light': '#faf4ed',
    'primary-dark': '#797593',
    background: '#faf4ed',
    'background-light': '#fffaf3',
    'background-dark': '#f2e9e1',
    'surface-1': '#ffffff',
    'surface-2': '#faf4ed',
    'surface-3': '#fffaf3',
    'surface-4': '#f2e9e1',
    text: '#575279',
    'text-secondary': '#9893ad',
    border: '#dfdad9',
    hover: '#fffaf3',
    header: '#fffaf3',
    shadow: 'rgba(87, 82, 121, 0.1)',
    success: '#56949f',
    warning: '#ea9d34',
    danger: '#b4637a',
    info: '#286983',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

const everforestLightTheme: Theme = {
  id: 'everforest_light',
  name: '青松翠竹',
  isDark: false,
  colors: {
    primary: '#3a94c5',
    'primary-light': '#fdf6e3',
    'primary-dark': '#2d7da1',
    background: '#fdf6e3',
    'background-light': '#f3efda',
    'background-dark': '#e9e5cf',
    'surface-1': '#ffffff',
    'surface-2': '#fdf6e3',
    'surface-3': '#f3efda',
    'surface-4': '#e9e5cf',
    text: '#5c6a72',
    'text-secondary': '#a8b5a5',
    border: '#e9e5cf',
    hover: '#f3efda',
    header: '#f3efda',
    shadow: 'rgba(92, 106, 114, 0.1)',
    success: '#8da101',
    warning: '#dfa000',
    danger: '#f85552',
    info: '#35a77c',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

const githubLightTheme: Theme = {
  id: 'github_light',
  name: '晴空雅境',
  isDark: false,
  colors: {
    primary: '#0969da',
    'primary-light': '#f6f8fa',
    'primary-dark': '#0550ae',
    background: '#ffffff',
    'background-light': '#f6f8fa',
    'background-dark': '#eaeef2',
    'surface-1': '#ffffff',
    'surface-2': '#f6f8fa',
    'surface-3': '#eaeef2',
    'surface-4': '#d0d7de',
    text: '#1F2328',
    'text-secondary': '#7d8590',
    border: '#d0d7de',
    hover: '#f3f4f6',
    header: '#f6f8fa',
    shadow: 'rgba(31, 35, 40, 0.1)',
    success: '#1a7f37',
    warning: '#9a6700',
    danger: '#cf222e',
    info: '#0969da',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

const githubDarkTheme: Theme = {
  id: 'github_dark',
  name: '墨韵沉香',
  isDark: true,
  colors: {
    primary: '#58a6ff',
    'primary-light': '#1F2937',
    'primary-dark': '#388bfd',
    background: '#0d1117',
    'background-light': '#161b22',
    'background-dark': '#010409',
    'surface-1': '#161b22',
    'surface-2': '#0d1117',
    'surface-3': '#010409',
    'surface-4': '#090c10',
    text: '#f0f0f0',
    'text-secondary': '#d7d7d7',
    border: '#30363d',
    hover: '#161b22',
    header: '#161b22',
    shadow: 'rgba(0, 0, 0, 0.3)',
    success: '#3fb950',
    warning: '#d29922',
    danger: '#f85149',
    info: '#58a6ff',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

const oneDarkTheme: Theme = {
  id: 'one_dark',
  name: '玄黛之美',
  isDark: true,
  colors: {
    primary: '#61afef',
    'primary-light': '#353b45',
    'primary-dark': '#528bff',
    background: '#282c34',
    'background-light': '#353b45',
    'background-dark': '#21252b',
    'surface-1': '#353b45',
    'surface-2': '#282c34',
    'surface-3': '#21252b',
    'surface-4': '#181a1f',
    text: '#f0f0f0',
    'text-secondary': '#d7d7d7',
    border: '#181a1f',
    hover: '#2c313a',
    header: '#21252b',
    shadow: 'rgba(0, 0, 0, 0.3)',
    success: '#98c379',
    warning: '#e5c07b',
    danger: '#e06c75',
    info: '#56b6c2',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

const rainbowTheme: Theme = {
  id: 'rainbow',
  name: '霓虹梦境',
  isDark: true,
  colors: {
    primary: '#ff3399',
    'primary-light': '#2a1f3a',
    'primary-dark': '#ff1493',
    background: '#191724',
    'background-light': '#1f1d2e',
    'background-dark': '#13111e',
    'surface-1': '#1f1d2e',
    'surface-2': '#191724',
    'surface-3': '#13111e',
    'surface-4': '#0f0d16',
    text: '#f0f0f0',
    'text-secondary': '#d7d7d7',
    border: '#524f67',
    hover: '#1f1d2e',
    header: '#191724',
    shadow: 'rgba(255, 105, 180, 0.3)',
    success: '#7fff00',
    warning: '#ffd700',
    danger: '#ff1493',
    info: '#00ffff',
    rainbow1: '#ff0000',
    rainbow2: '#ff8c00',
    rainbow3: '#ffff00',
    rainbow4: '#00ff00',
    rainbow5: '#00ffff',
    rainbow6: '#0000ff',
    rainbow7: '#ff00ff',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

// 添加高对比度主题
const highContrastTheme: Theme = {
  id: 'high_contrast',
  name: '黑白交响',
  isDark: true,
  colors: {
    primary: '#ffff00',
    'primary-light': '#2a2a2a',
    'primary-dark': '#ffff33',
    background: '#000000',
    'background-light': '#1a1a1a',
    'background-dark': '#000000',
    'surface-1': '#2a2a2a',
    'surface-2': '#1a1a1a',
    'surface-3': '#0a0a0a',
    'surface-4': '#000000',
    text: '#f0f0f0',
    'text-secondary': '#d7d7d7',
    border: '#ffffff',
    hover: '#2a2a2a',
    header: '#1a1a1a',
    shadow: 'rgba(255, 255, 255, 0.2)',
    success: '#00ff00',
    warning: '#ffff00',
    danger: '#ff0000',
    info: '#00ffff',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

// 添加护眼主题
const eyeCareTheme: Theme = {
  id: 'eye_care',
  name: '青玉护目',
  isDark: false,
  colors: {
    primary: '#5b8c5a',
    'primary-light': '#f3f6f3',
    'primary-dark': '#3d5e3c',
    background: '#f0f2eb',
    'background-light': '#f3f6f3',
    'background-dark': '#e6e9e1',
    'surface-1': '#ffffff',
    'surface-2': '#f3f6f3',
    'surface-3': '#e6e9e1',
    'surface-4': '#d1d9cc',
    text: '#2c3338',
    'text-secondary': '#778088',
    border: '#d1d9cc',
    hover: '#f3f6f3',
    header: '#f3f6f3',
    shadow: 'rgba(0, 0, 0, 0.05)',
    success: '#5b8c5a',
    warning: '#8c7355',
    danger: '#8c5a5a',
    info: '#557b8c',
    selected: 'var(--el-color-primary-light-9)',
    'selected-hover': 'var(--el-color-primary-light-8)',
    'border-active': 'var(--el-color-primary-light-5)',
  },
}

// 导出所有官方主题
export const officialThemes: Theme[] = [
  catppuccinLatteTheme,
  rosePineTheme,
  everforestLightTheme,
  githubLightTheme,
  githubDarkTheme,
  oneDarkTheme,
  rainbowTheme,
  highContrastTheme,
  eyeCareTheme,
]
