/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthorizationManager: typeof import('./components/auth/AuthorizationManager.vue')['default']
    BaseEditor: typeof import('./components/editor/BaseEditor.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor.vue')['default']
    EditorConfig: typeof import('./components/editor/EditorConfig.vue')['default']
    EditorToolbar: typeof import('./components/editor/EditorToolbar.vue')['default']
    EnvironmentManager: typeof import('./components/EnvironmentManager.vue')['default']
    ExampleMessageIcon: typeof import('./components/icons/ExampleMessageIcon.vue')['default']
    ExportIcon: typeof import('./components/icons/ExportIcon.vue')['default']
    FavoriteManager: typeof import('./components/FavoriteManager.vue')['default']
    FeatureCard: typeof import('./components/home/FeatureCard.vue')['default']
    FolderManager: typeof import('./components/FolderManager.vue')['default']
    GeneralSettings: typeof import('./components/settings/GeneralSettings.vue')['default']
    HeadersManager: typeof import('./components/HeadersManager.vue')['default']
    ImportIcon: typeof import('./components/icons/ImportIcon.vue')['default']
    JsonEditor: typeof import('./components/editor/JsonEditor.vue')['default']
    LayoutSettings: typeof import('./components/settings/LayoutSettings.vue')['default']
    LogoIcon: typeof import('./components/icons/LogoIcon.vue')['default']
    MetadataEditor: typeof import('./components/rpc/MetadataEditor.vue')['default']
    RequestDetailsDrawer: typeof import('./components/RequestDetailsDrawer.vue')['default']
    RequestHistory: typeof import('./components/history/RequestHistory.vue')['default']
    RequestHistoryTable: typeof import('./components/history/RequestHistoryTable.vue')['default']
    RequestPanel: typeof import('./components/RequestPanel.vue')['default']
    RequestRegion: typeof import('./components/rpc/RequestRegion.vue')['default']
    ResponseHeaders: typeof import('./components/ResponseHeaders.vue')['default']
    ResponseViewer: typeof import('./components/ResponseViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RPCMessageEditor: typeof import('./components/rpc/RPCMessageEditor.vue')['default']
    RPCMethodSelector: typeof import('./components/rpc/RPCMethodSelector.vue')['default']
    RpcRequestRegion: typeof import('./components/rpc/RpcRequestRegion.vue')['default']
    Settings: typeof import('./components/settings/Settings.vue')['default']
    SettingsPanel: typeof import('./components/settings/SettingsPanel.vue')['default']
    ShortcutsSettings: typeof import('./components/settings/ShortcutsSettings.vue')['default']
    TabManager: typeof import('./components/tabs/TabManager.vue')['default']
    ThemeEditor: typeof import('./components/settings/ThemeEditor.vue')['default']
    ThemePreviewCard: typeof import('./components/common/ThemePreviewCard.vue')['default']
    ThemeSettings: typeof import('./components/settings/ThemeSettings.vue')['default']
    VueDevTools: typeof import('./components/debug/VueDevTools.vue')['default']
    WorkspaceSetup: typeof import('./components/WorkspaceSetup.vue')['default']
    YamlEditor: typeof import('./components/editor/YamlEditor.vue')['default']
  }
}
